package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"

	"forgejo.coilysiren.me/coilyco-gaming/sirens-echo/internal/community"
)

// The rendered prompt is the model's whole instruction surface, and it is
// assembled from several files. See docs/sirens-echo-prompt.md.
const renderedDir = "agent/rendered"

var trackedDefinitions = []string{
	"agent/sirens-echo.yaml",
	"agent/sirens-deep.yaml",
}

// sampleHistory and sampleRequest keep the user-prompt section deterministic,
// so a snapshot diff only ever reflects a change in the harness.
var sampleHistory = []community.TranscriptEntry{
	{Author: "member", Content: "Is the server up?"},
	{Author: "CoilyCo", Content: "Checking now."},
}

var sampleRequest = community.TranscriptEntry{
	Author:  "member",
	Content: "What changed in the last update?",
}

func main() {
	check := flag.Bool("check", false, "fail on a stale snapshot instead of rewriting it")
	flag.Parse()

	stale := make([]string, 0, len(trackedDefinitions))
	for _, path := range trackedDefinitions {
		name := strings.TrimSuffix(filepath.Base(path), ".yaml")
		target := filepath.Join(renderedDir, name+".prompt.txt")
		rendered, err := render(path)
		if err != nil {
			log.Fatalf("render %s: %v", path, err)
		}
		existing, readErr := os.ReadFile(target)
		if readErr == nil && string(existing) == rendered {
			fmt.Printf("current %s (%d bytes)\n", target, len(rendered))
			continue
		}
		if *check {
			stale = append(stale, target)
			continue
		}
		if err := os.MkdirAll(renderedDir, 0o755); err != nil {
			log.Fatalf("create %s: %v", renderedDir, err)
		}
		if err := os.WriteFile(target, []byte(rendered), 0o644); err != nil {
			log.Fatalf("write %s: %v", target, err)
		}
		fmt.Printf("wrote %s (%d bytes)\n", target, len(rendered))
	}
	if len(stale) > 0 {
		log.Fatalf(
			"stale prompt snapshots: %s\nrun `ward exec prompt-dump` and commit the result",
			strings.Join(stale, ", "),
		)
	}
}

func render(path string) (string, error) {
	definition, err := community.LoadDefinition(path)
	if err != nil {
		return "", err
	}
	localPolicy, err := community.LoadSkillpack(definition.LocalSkillRoots)
	if err != nil {
		return "", err
	}
	systemPrompt := community.BuildSystemPrompt(definition, localPolicy)
	if err := community.ValidateSystemPrompt(definition, systemPrompt); err != nil {
		return "", err
	}
	userPrompt := community.BuildUserPrompt(sampleHistory, sampleRequest)

	var output strings.Builder
	fmt.Fprintf(&output, "Generated by `ward exec prompt-dump`. Do not edit by hand.\n")
	fmt.Fprintf(&output, "Definition: %s\n", path)
	fmt.Fprintf(&output, "Identity: %s\n", definition.Identity)
	fmt.Fprintf(&output, "Response style: %s\n", definition.ResponseStyle)
	fmt.Fprintf(&output, "Local policy roots: %s\n", strings.Join(definition.LocalSkillRoots, ", "))
	fmt.Fprintf(&output, "System prompt bytes: %d\n", len(systemPrompt))
	fmt.Fprintf(&output, "\n===== SYSTEM PROMPT =====\n\n%s", systemPrompt)
	fmt.Fprintf(&output, "\n===== USER PROMPT (fixed sample) =====\n\n%s\n", userPrompt)
	return output.String(), nil
}
