package community

import (
	"encoding/json"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// A role snapshot records what a baked bundle selected, not what it says.
// See docs/sirens-echo-compose.md.

// bundleManifest is the subset of agent-compose's manifest this repository
// gates on. Digests are deliberately absent.
type bundleManifest struct {
	Format        string   `json:"format"`
	Role          string   `json:"role"`
	RoleSkill     string   `json:"role_skill"`
	ModelTier     string   `json:"model_tier"`
	Personalities []string `json:"personalities"`
	Sources       []string `json:"sources"`
	// Identity is recorded because a request may now rename the seat, and a
	// rename no record carries is a silent one. See docs/sirens-echo-identity.md.
	Identity struct {
		Seats []struct {
			Name     string `json:"name"`
			Pronouns string `json:"pronouns"`
		} `json:"seats"`
	} `json:"identity"`
	Content []struct {
		ID string `json:"id"`
	} `json:"content"`
}

// RoleBundle is one baked role, ready to render or compare.
type RoleBundle struct {
	Role     string
	Manifest bundleManifest
	// Skills is the delivered set as `<source>/<skill>`. The manifest's content
	// list covers the roster identity only, so this comes off disk.
	Skills       []string
	SystemPrompt string
}

// bundleSkills enumerates the delivered skills. Directory names are the stable
// identifiers; the bodies underneath are what move with upstream.
func bundleSkills(dir string) ([]string, error) {
	root := filepath.Join(dir, "content", "skills")
	sources, err := os.ReadDir(root)
	if err != nil {
		return nil, fmt.Errorf("read delivered skills: %w", err)
	}
	skills := make([]string, 0, 16)
	for _, source := range sources {
		if !source.IsDir() {
			continue
		}
		// agent-compose escapes a source name for the filesystem, so `roster:core`
		// lands as `roster%3Acore`.
		name, err := url.PathUnescape(source.Name())
		if err != nil {
			name = source.Name()
		}
		entries, err := os.ReadDir(filepath.Join(root, source.Name()))
		if err != nil {
			return nil, fmt.Errorf("read source %s: %w", name, err)
		}
		for _, entry := range entries {
			if entry.IsDir() {
				skills = append(skills, name+"/"+entry.Name())
			}
		}
	}
	sort.Strings(skills)
	return skills, nil
}

// LoadRoleBundles reads every baked role and builds the prompt each produces,
// so a bundle that cannot make a valid one fails here rather than at startup.
func LoadRoleBundles(
	bundleDir string,
	definition Definition,
	principal Principal,
	localSkillpack string,
) ([]RoleBundle, error) {
	entries, err := os.ReadDir(bundleDir)
	if err != nil {
		return nil, fmt.Errorf("read bundle directory: %w", err)
	}
	loaded := make([]RoleBundle, 0, len(entries))
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		role := entry.Name()
		dir := filepath.Join(bundleDir, role)
		raw, err := os.ReadFile(filepath.Join(dir, "manifest.json"))
		if err != nil {
			return nil, fmt.Errorf("role %s: read manifest: %w", role, err)
		}
		var manifest bundleManifest
		if err := json.Unmarshal(raw, &manifest); err != nil {
			return nil, fmt.Errorf("role %s: parse manifest: %w", role, err)
		}
		if manifest.Role != role {
			return nil, fmt.Errorf(
				"role %s: manifest names role %q, so the bundle is filed under the wrong slug",
				role,
				manifest.Role,
			)
		}
		body, err := LoadBundle(dir)
		if err != nil {
			return nil, fmt.Errorf("role %s: %w", role, err)
		}
		prompt := BuildSystemPrompt(definition, principal, body, localSkillpack)
		// The point of the gate: a role whose bundle silently failed to compose
		// must not ship as a quietly neutral agent.
		if err := ValidateSystemPrompt(definition, principal, prompt); err != nil {
			return nil, fmt.Errorf("role %s: %w", role, err)
		}
		skills, err := bundleSkills(dir)
		if err != nil {
			return nil, fmt.Errorf("role %s: %w", role, err)
		}
		loaded = append(loaded, RoleBundle{
			Role:         role,
			Manifest:     manifest,
			Skills:       skills,
			SystemPrompt: prompt,
		})
	}
	if len(loaded) == 0 {
		return nil, fmt.Errorf("no baked role under %s", bundleDir)
	}
	sort.Slice(loaded, func(i, j int) bool { return loaded[i].Role < loaded[j].Role })
	return loaded, nil
}

// RenderRoleSnapshot renders the tracked record for one role: the selection and
// none of the bodies, so only a change in what the role pulls moves it.
func RenderRoleSnapshot(bundle RoleBundle) string {
	manifest := bundle.Manifest
	sources := append([]string(nil), manifest.Sources...)
	sort.Strings(sources)
	personalities := append([]string(nil), manifest.Personalities...)
	sort.Strings(personalities)

	var output strings.Builder
	fmt.Fprintf(&output, "Generated by `just role-snapshot`. Do not edit by hand.\n")
	fmt.Fprintf(&output, "Role: %s\n", manifest.Role)
	fmt.Fprintf(&output, "Role skill: %s\n", manifest.RoleSkill)
	if seats := manifest.Identity.Seats; len(seats) > 0 {
		fmt.Fprintf(&output, "Seat: %s (%s)\n", seats[0].Name, seats[0].Pronouns)
	}
	fmt.Fprintf(&output, "Model tier: %s\n", manifest.ModelTier)
	fmt.Fprintf(&output, "Personalities: %s\n", strings.Join(personalities, ", "))
	fmt.Fprintf(&output, "Sources: %s\n", strings.Join(sources, ", "))
	fmt.Fprintf(&output, "Skills: %d\n", len(bundle.Skills))
	output.WriteString("\n===== SELECTION =====\n\n")
	for _, skill := range bundle.Skills {
		fmt.Fprintf(&output, "%s\n", skill)
	}
	return output.String()
}
